apiVersion: v1
kind: Service
metadata:
  namespace: funceasy
  name: funceasy-website
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: funceasy-website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: funceasy
  name: funceasy-website
spec:
  selector:
    matchLabels:
      app: funceasy-website
  template:
    metadata:
      labels:
        app: funceasy-website
    spec:
      containers:
        - image: ziqiancheng/funceasy-website
          name: funceasy-website
          ports:
            - containerPort: 80